In [1]:
import numpy as np

R = np.array([[4, np.NaN, np.NaN, 2, np.NaN],
             [np.NaN, 5, np.NaN, 3, 1],
             [np.NaN, np.NaN, 3, 4, 4],
             [5, 2, 1, 2, np.NaN]])

num_users, num_items = R.shape
K=3

np.random.seed(1)
P = np.random.normal(scale=1./K, size = (num_users, K))
Q = np.random.normal(scale=1./K, size = (num_items, K))

In [2]:
from sklearn.metrics import mean_squared_error

def get_rmse(R,P,Q,non_zeros):
    error = 0
    full_pred_matrix = np.dot(P, Q.T)
    
    x_non_zero_ind = [non_zero[0] for non_zero in non_zeros]
    y_non_zero_ind = [non_zero[1] for non_zero in non_zeros]
    R_non_zeros = R[x_non_zero_ind, y_non_zero_ind]
    full_pred_matrix_non_zeros = full_pred_matrix[x_non_zero_ind, y_non_zero_ind]
    mse = mean_squared_error(R_non_zeros, full_pred_matrix_non_zeros)
    rmse = np.sqrt(mse)
    
    return mse

In [3]:
non_zeros = [(i,j,R[i,j]) for i in range(num_users) for j in range(num_items) if R[i,j] > 0 ]

steps = 1000
learning_rate = 0.01
r_lambda = 0.01

for step in range(steps):
    for i, j, r in non_zeros:
        eij = r - np.dot(P[i,:], Q[j,:].T)
        P[i,:] = P[i,:] + learning_rate*(eij * Q[j,:] - r_lambda*P[i,:])
        Q[j,:] = Q[j,:] + learning_rate*(eij * P[i,:] - r_lambda*Q[j,:])
        rmse = get_rmse(R, P, Q, non_zeros)
        if (step % 50) == 0 :
            print("### iteration step : ", step, " rmse : ", rmse)

### iteration step :  0  rmse :  10.636436824054075
### iteration step :  0  rmse :  10.63021188824725
### iteration step :  0  rmse :  10.588414505005085
### iteration step :  0  rmse :  10.576534154532787
### iteration step :  0  rmse :  10.577684928273099
### iteration step :  0  rmse :  10.56947042640335
### iteration step :  0  rmse :  10.557593058694795
### iteration step :  0  rmse :  10.545713778795802
### iteration step :  0  rmse :  10.51008454903946
### iteration step :  0  rmse :  10.497894263795414
### iteration step :  0  rmse :  10.498680507861131
### iteration step :  0  rmse :  10.489858008094606
### iteration step :  50  rmse :  0.25031919103920597
### iteration step :  50  rmse :  0.25016165525667544
### iteration step :  50  rmse :  0.24899702001763332
### iteration step :  50  rmse :  0.24884967132378844
### iteration step :  50  rmse :  0.24895299109551006
### iteration step :  50  rmse :  0.2483351492963937
### iteration step :  50  rmse :  0.24841736164175987
##

### iteration step :  650  rmse :  0.0002780319915179904
### iteration step :  650  rmse :  0.00028166558434741183
### iteration step :  650  rmse :  0.00027707926495828015
### iteration step :  650  rmse :  0.00027447015425926174
### iteration step :  650  rmse :  0.0002782254364888111
### iteration step :  650  rmse :  0.0002788417147559163
### iteration step :  650  rmse :  0.0002726137065605426
### iteration step :  650  rmse :  0.00027196062624240176
### iteration step :  650  rmse :  0.00026181001054218964
### iteration step :  650  rmse :  0.00026605235859624197
### iteration step :  650  rmse :  0.00026873594791246703
### iteration step :  650  rmse :  0.00027704726688556014
### iteration step :  700  rmse :  0.0002768351047716055
### iteration step :  700  rmse :  0.00028029244591744876
### iteration step :  700  rmse :  0.00027567701549476237
### iteration step :  700  rmse :  0.00027312369481384156
### iteration step :  700  rmse :  0.0002768826805781003
### iteration step :

In [4]:
pred_matrix = np.dot(P, Q.T)
print("예측행렬: \n", np.round(pred_matrix, 3))

예측행렬: 
 [[3.991 0.897 1.306 2.002 1.663]
 [6.696 4.978 0.979 2.981 1.003]
 [6.677 0.391 2.987 3.977 3.986]
 [4.968 2.005 1.006 2.017 1.14 ]]
