<a href="https://colab.research.google.com/github/gayun99/esaa21-2/blob/main/nlp_embedding-modeling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install konlpy

     |████████████████████████████████| 19.4 MB 1.3 MB/s 
     |████████████████████████████████| 86 kB 5.4 MB/s 
     |████████████████████████████████| 448 kB 46.7 MB/s 
  Attempting uninstall: beautifulsoup4
    Found existing installation: beautifulsoup4 4.6.3
    Uninstalling beautifulsoup4-4.6.3:
      Successfully uninstalled beautifulsoup4-4.6.3


In [ ]:
from konlpy.tag import Kkma
kkma = Kkma()
sentence = '데이콘에서 다양한 컴피티션을 즐기면서 실력있는 데이터 분석가로 성장하세요!!.'

print("형태소 단위로 분리")
print("-------------------")
print(kkma.morphs(sentence))
print(" ")
print("문장에서 명사 추출")
print("-------------------")
print(kkma.nouns(sentence))
print(" ")
print("품사 태킹(PoS)")
print("-------------------")
print(kkma.pos(sentence))

형태소 단위로 분리
-------------------
['데이', '콘', '에서', '다양', '하', 'ㄴ', '컴피티션', '을', '즐기', '면서', '실력', '있', '는', '데이터', '분석가', '로', '성장', '하', '세요', '!!', '.']
 
문장에서 명사 추출
-------------------
['데이', '데이콘', '콘', '다양', '컴피티션', '실력', '데이터', '분석가', '성장']
 
품사 태킹(PoS)
-------------------
[('데이', 'NNG'), ('콘', 'NNG'), ('에서', 'JKM'), ('다양', 'NNG'), ('하', 'XSV'), ('ㄴ', 'ETD'), ('컴피티션', 'UN'), ('을', 'JKO'), ('즐기', 'VV'), ('면서', 'ECE'), ('실력', 'NNG'), ('있', 'VV'), ('는', 'ETD'), ('데이터', 'NNG'), ('분석가', 'NNG'), ('로', 'JKM'), ('성장', 'NNG'), ('하', 'XSV'), ('세요', 'EFN'), ('!!', 'SW'), ('.', 'SF')]


In [ ]:
from konlpy.tag import Okt
Okt = Okt()
sentence = '데이콘에서 다양한 컴피티션을 즐기면서 실력있는 데이터 분석가로 성장하세요!!.'

print("형태소 단위로 분리")
print("-------------------")
print(Okt.morphs(sentence))
print(" ")
print("문장에서 명사 추출")
print("-------------------")
print(Okt.nouns(sentence))
print(" ")
print("품사 태킹(PoS)")
print("-------------------")
print(Okt.pos(sentence))


형태소 단위로 분리
-------------------
['데', '이콘', '에서', '다양한', '컴피티션', '을', '즐기면서', '실력', '있는', '데이터', '분석', '가로', '성장하세요', '!!.']
 
문장에서 명사 추출
-------------------
['데', '이콘', '컴피티션', '실력', '데이터', '분석', '가로']
 
품사 태킹(PoS)
-------------------
[('데', 'Noun'), ('이콘', 'Noun'), ('에서', 'Josa'), ('다양한', 'Adjective'), ('컴피티션', 'Noun'), ('을', 'Josa'), ('즐기면서', 'Verb'), ('실력', 'Noun'), ('있는', 'Adjective'), ('데이터', 'Noun'), ('분석', 'Noun'), ('가로', 'Noun'), ('성장하세요', 'Adjective'), ('!!.', 'Punctuation')]


In [ ]:
from konlpy.tag import Kkma
kkma = Kkma()

sentence = '성장했었다.'

print("품사 태킹(PoS)")
print("----------------------")
print(kkma.pos(sentence))

품사 태킹(PoS)
----------------------
[('성장', 'NNG'), ('하', 'XSV'), ('었', 'EPT'), ('었', 'EPT'), ('다', 'EFN'), ('.', 'SF')]


In [ ]:
sentence = '성장하였었다.'

print("품사 태킹(PoS)")
print("----------------------")
print(kkma.pos(sentence))

품사 태킹(PoS)
----------------------
[('성장', 'NNG'), ('하', 'XSV'), ('였', 'EPT'), ('었', 'EPT'), ('다', 'EFN'), ('.', 'SF')]


In [ ]:
from konlpy.tag import Okt
import re
tokenizer = Okt()
def text_preprocessing(text,tokenizer):
    
    stopwords = ['을', '를', '이', '가', '은', '는']
    
    txt = re.sub('[^가-힣a-z]', ' ', text)
    token = tokenizer.morphs(txt)
    token = [t for t in token if t not in stopwords]
        
    return token

ex_text = "이번에 새롭게 개봉한 영화의 배우들은 모두 훌륭한 연기력과 아름다운 목소리를 갖고 있어!!"
example_pre= text_preprocessing(ex_text,tokenizer)

In [ ]:
def text_preprocessing(text_list):
    
    stopwords = ['을', '를', '이', '가', '은', '는', 'null'] #불용어 설정
    tokenizer = Okt() #형태소 분석기 
    token_list = []
    
    for text in text_list:
        txt = re.sub('[^가-힣a-z]', ' ', text) #한글과 영어 소문자만 남기고 다른 글자 모두 제거
        token = tokenizer.morphs(txt) #형태소 분석
        token = [t for t in token if t not in stopwords or type(t) != float] #형태소 분석 결과 중 stopwords에 해당하지 않는 것만 추출
        token_list.append(token)
        
    return token_list, tokenizer


# facebook fasttext

In [ ]:
cd /content

/content


In [ ]:
pip install fasttext

     |████████████████████████████████| 68 kB 6.0 MB/s 
  Using cached pybind11-2.7.1-py2.py3-none-any.whl (200 kB)


In [ ]:
import fasttext

# # Word Representation
# # Skipgram model :
# skip_model = fasttext.train_unsupervised('./author.txt', model='skipgram')
# skip_model.save_model("skip_model.bin")
# print(skip_model.words)
# # or, cbow model :
# cbow_model = fasttext.train_unsupervised('./author.txt', model='cbow')
# cbow_model.save_model("cbow_model.bin")
# print(cbow_model.words)

#  디폴트로 돌리면 0.56

import pandas as pd
import numpy as np

train = pd.read_csv('train.csv')

file = open('fasttexttrain.txt','w+')
for i in train.index:
    line = '__label__' + str(train['author'][i])+' '+train['text'][i]
    file.write(line+"\n")

# Text Classification
# input             # training file path (required)
# model             # unsupervised fasttext model {cbow, skipgram} [skipgram]
# lr                # learning rate [0.05]
# dim               # size of word vectors [100]
# ws                # size of the context window [5]
# epoch             # number of epochs [5]
# minCount          # minimal number of word occurences [5]
# minn              # min length of char ngram [3]
# maxn              # max length of char ngram [6]
# neg               # number of negatives sampled [5]
# wordNgrams        # max length of word ngram [1]
# loss              # loss function {ns, hs, softmax, ova} [ns]
# bucket            # number of buckets [2000000]
# thread            # number of threads [number of cpus]
# lrUpdateRate      # change the rate of updates for the learning rate [100]
# t                 # sampling threshold [0.0001]
# verbose           # verbose [2]

text_clf_model = fasttext.train_supervised('fasttexttrain.txt', epoch=30, minCount=2, maxn=10, verbose=0)
print(text_clf_model.words)
print(text_clf_model.labels)

reuslt = text_clf_model.predict("He was almost choking. There was so much, so much he wanted to say, but strange exclamations were all that came from his lips. The Pole gazed fixedly at him, at the bundle of notes in his hand; looked at odin, and was in evident perplexity.", k=5)
print(reuslt)

test = pd.read_csv('test_x.csv')
submission = pd.read_csv('sample_submission.csv', index_col=False)

ModuleNotFoundError: ignored

In [ ]:
for i in test.index:
  lable, proba = text_clf_model.predict(test['text'][i], k=5)
  for la, pr in zip(lable,proba):
    if '__label__0' == la:
      submission.loc[i,'0'] = pr
    elif '__label__1' == la:
      submission.loc[i,'1'] = pr
    elif '__label__2' == la:
      submission.loc[i,'2'] = pr
    elif '__label__3' == la:
      submission.loc[i,'3'] = pr
    elif '__label__4' == la:
      submission.loc[i,'4'] = pr

submission.to_csv('result_fasttext.csv',index=False)
print('end')

#vectorization

In [ ]:
from konlpy.tag import Okt
import re

Okt = Okt()

sentences = ['자연어 처리는 정말 정말 즐거워.', '즐거운 자연어 처리 다같이 해보자.']
tokens = []

for sentence in sentences:
    sentence = re.sub('[^가-힣a-z]', ' ', sentence) #간단한 전처리
    token = (Okt.morphs(sentence)) #형태소 분석기를 이용햔 토큰 나누기
    tokens.append(' '.join(token))

print("형태소 단위로 문장 분리")
print("----------------------")
print(tokens)
 

형태소 단위로 문장 분리
----------------------
['자연어 처리 는 정말 정말 즐거워', '즐거운 자연어 처리 다 같이 해보자']


In [ ]:
# one hot incodeing

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical

t = Tokenizer()
t.fit_on_texts(tokens)
print("각 토큰에게 고유의 정수 부여")
print("----------------------")
print(t.word_index) 
print(" ")

s1=t.texts_to_sequences(tokens)[0] 
print("부여된 정수로 표시된 문장1")
print("----------------------")
print(s1)
print(" ")

s2=t.texts_to_sequences(tokens)[1]
print("부여된 정수로 표시된 문장2")
print("----------------------")
print(s2)
print(" ")

s1_one_hot = to_categorical(s1)
print("문장1의 one-hot-encoding")
print("----------------------")
print(s1_one_hot)
print(" ")

s2_one_hot = to_categorical(s2)
print("문장2의 one-hot-encoding")
print("----------------------")
print(s2_one_hot)

각 토큰에게 고유의 정수 부여
----------------------
{'자연어': 1, '처리': 2, '정말': 3, '는': 4, '즐거워': 5, '즐거운': 6, '다': 7, '같이': 8, '해보자': 9}
 
부여된 정수로 표시된 문장1
----------------------
[1, 2, 4, 3, 3, 5]
 
부여된 정수로 표시된 문장2
----------------------
[6, 1, 2, 7, 8, 9]
 
문장1의 one-hot-encoding
----------------------
[[0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
 
문장2의 one-hot-encoding
----------------------
[[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
# count vectorization
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
vectors = vectorizer.fit_transform(tokens) 

print(vectorizer.get_feature_names())
print(vectors.toarray())

['같이', '자연어', '정말', '즐거운', '즐거워', '처리', '해보자']
[[0 1 2 0 1 1 0]
 [1 1 0 1 0 1 1]]


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(min_df=0)
tfidf_vectorizer = tfidf.fit_transform(tokens) 

#tf-idf dictionary    
tfidf_dict = tfidf.get_feature_names()
print(tfidf_dict)
print(tfidf_vectorizer.toarray())

['같이', '자연어', '정말', '즐거운', '즐거워', '처리', '해보자']
[[0.         0.29017021 0.81564821 0.         0.4078241  0.29017021
  0.        ]
 [0.49922133 0.35520009 0.         0.49922133 0.         0.35520009
  0.49922133]]


In [ ]:
import pandas as pd
import numpy as np

train = pd.read_csv('train.csv')

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

def text2sequence(train_text, max_len=100):
    
    tokenizer = Tokenizer() #keras의 vectorizing 함수 호출
    tokenizer.fit_on_texts(train_text) #train 문장에 fit
    train_X_seq = tokenizer.texts_to_sequences(train_text) #각 토큰들에 정수 부여
    vocab_size = len(tokenizer.word_index) + 1 #모델에 알려줄 vocabulary의 크기 계산
    print('vocab_size : ', vocab_size)
    X_train = pad_sequences(train_X_seq, maxlen = max_len) #설정한 문장의 최대 길이만큼 padding
    
    return X_train, vocab_size, tokenizer

train_X, vocab_size, vectorizer = text2sequence(train['text'], max_len = 100)

vocab_size :  42331


#9/27 embedding

In [ ]:
# from keras import Sequential
# from keras.layers import Embedding
# max_len = 100
# model = Sequential()
# model.add(Embedding(vocab_size, 128, imput_length = max_len))

In [ ]:
#import gensim
#word2vec = gensim.models.KeyedVectors.load_word2vec_format('GoogleNews-vectors-negative300.bin.gz',binary = True)

In [ ]:
#embedding_matrix = np.zeros((vocab_size,300))
# for index, word in enumerate(vocabulary):
#   if word in word2vec:
#     embedding_vector = word2vec[word]
#     embedding_matrix[i] = embedding_vector
#   else:
#     print("word2vec에 없는 단어입니다.")
#     break

In [ ]:
#model = Sequential()
#model.add(Embedding(vocab_size, 300, weights = [embedding_matrix],input_length = max_len))

##glove

In [ ]:
# glove = dict()
# f = open('./glove.txt')
# for line in f:
#     values = line.split()
#     word = values[0]
#     vector = asarray(values[1:], dtype='float32')
#     glove[word] = vector
# f.close()

In [ ]:
# embedding_matrix = np.zeros((vocab_size, 300)) #300차원의 임베딩 매트릭스 생성

# for index, word in enumerate(vocabulary): #vocabulary에 있는 토큰들을 하나씩 넘겨줍니다.
#     if word in word2vec: #넘겨 받은 토큰이 word2vec에 존재하면(이미 훈련이 된 토큰이라는 뜻)
#         embedding_vector = word2vec[word] #해당 토큰에 해당하는 vector를 불러오고
#         embedding_matrix[i] = embedding_vector #해당 위치의 embedding_mxtrix에 저장합니다.
#     else:
#         print("word2vec에 없는 단어입니다.")
#         break

In [ ]:
#model = Sequential()
#model.add(Embedding(vocab_size, 300,weights = [embedding_matrx], input_length = max_len))

In [ ]:
#from gensim.models.keyedvectors import KeyedVectors
#FastText = KeyedVectors.load_word2vec_format('./fasttext.bin', binary = True)


In [ ]:
# embedding_matrix = np.zeros((vocab_size, 300)) #300차원의 임베딩 매트릭스 생성

# for index, word in enumerate(vocabulary): #vocabulary에 있는 토큰들을 하나씩 넘겨줍니다.
#     if word in word2vec: #넘겨 받은 토큰이 word2vec에 존재하면(이미 훈련이 된 토큰이라는 뜻)
#         embedding_vector = word2vec[word] #해당 토큰에 해당하는 vector를 불러오고
#         embedding_mxtrix[i] = embedding_vector #해당 위치의 embedding_mxtrix에 저장합니다.

In [ ]:
# model = Sequential()
# model.add(Embedding(vocab_size, 300,weights = [embedding_matrx], input_length = max_len))

In [ ]:
# def text_preprocessing(text_list):
    
#     stopwords = ['을', '를', '이', '가', '은', '는', 'null']
#     tokenizer = Okt()
    
#     for text in tqdm.tqdm(text_list):
#         txt = re.sub('[^가-힣a-z]', ' ', text.lower())
#         token = tokenizer.morphs(txt)
#         token = [t for t in token if t not in stopwords or type(t) != float]
        
#     return token, tokenizer

# train['token'], okt = text_preprocessing(train['content'])

In [ ]:
# def text2sequence(train_text, max_len=1000):
    
#     tokenizer = Tokenizer()
#     tokenizer.fit_on_texts(train_text)
#     train_X_seq = tokenizer.texts_to_sequences(train_text)
#     vocab_size = len(tokenizer.word_index) + 1
#     print('vocab_size : ', vocab_size)
#     X_train = pad_sequences(train_X_seq, maxlen = max_len)
#     return X_train, vocab_size, tokenizer

# train_y = train['info']
# train_X, vocab_size, vectorizer = text2sequence(train['token'], max_len = 100)
# print(train_X.shape, train_y.shape)

In [ ]:
# word2vec = gensim.models.KeyedVectors.load_word2vec_format('GoogleNews-vectors-negative300.bin.gz', binary = True)
# embedding_matrix = np.zeros((vocab_size, 300))

# for index, word in enumerate(vocabulary):
#     if word in word2vec
#         embedding_vector = word2vec[word] 
#         embedding_mxtrix[i] = embedding_vector 
#     else:
#         print("word2vec에 없는 단어입니다.")
#         break

In [ ]:
# word2vec = gensim.models.KeyedVectors.load_word2vec_format('GoogleNews-vectors-negative300.bin.gz', binary = True)
# embedding_matrix = np.zeros((vocab_size, 300))

# for index, word in enumerate(vocabulary):
#     if word in word2vec
#         embedding_vector = word2vec[word] 
#         embedding_mxtrix[i] = embedding_vector 
#     else:
#         print("word2vec에 없는 단어입니다.")
#         break